integration: Remove dangling container and container names (#19)
Fixes a flaky minio error when running `go test -v ./...` in rapid
succession due to a bucket already existing.

```
$ go test -v ./...
minio is up
=== RUN   TestIntegration
    integration_test.go:141: operation error S3: CreateBucket, https response error StatusCode: 409, RequestID: 1782341B6096C63C, HostID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, BucketAlreadyOwnedByYou: 
--- FAIL: TestIntegration (0.00s)
```